# config/descriptions.yaml
elite: "Elite Series Combo – 3 Piece Perfection<br><br>
<span class='text-b font-medium text-lime-300 mb-1'>
1. Elegant Album Cover<br>
2. Premium Album Box<br>
3. Matching Designer Bag<br><br>
</span>
<div class='max-w-xl mx-auto'>
  Personalized to make every delivery special. The album cover and box feature UV-printed couple names, while the matching bag carries your company logo, adding a touch of class and brand presence.
</div>
"