colors:
  - name: Velvet Green
    image: velvet-green.jpg
    color: "#1a1a1a"
  - name: Butter Cream
    image: butter-cream.jpg
    color: "#d2b48c"
  - name: Cloud Grey
    image: cloud-grey.jpg
    color: "#f5f5f5"    
  - name: Dark Brown
    image: dark-brown.jpg
    color: "#1a1a1a"
  - name: Dark Knight
    image: dark-knight.jpg
    color: "#d2b48c"
  - name: Deep Blue
    image: deep-blue.jpg
    color: "#d2b48c"
  - name: Dove Brown
    image: dove-brown.jpg
    color: "#f5f5f5"
  - name: Euro Green
    image: euro-green.jpg
    color: "#f5f5f5" 
  - name: Forest Green
    image: forest-green.jpg
    color: "#1a1a1a"
  - name: Golden Desert
    image: golden-desert.jpg
    color: "#d2b48c"    
  - name: Light Desert
    image: light-desert.jpg
    color: "#1a1a1a"
  - name: Mehndi Green
    image: mehndi-green.jpg
    color: "#d2b48c"
  - name: Navy Blue
    image: navy-blue.jpg
    color: "#1a1a1a"
  - name: Rose Pink
    image: rose-pink.jpg
    color: "#f5f5f5" 
  - name: Velvet Blue
    image: velvet-blue.jpg
    color: "#1a1a1a"
  - name: Royal Red
    image: royal-red.jpg
    color: "#d2b48c"   
  - name: Ruby Red
    image: ruby-red.jpg
    color: "#1a1a1a"
  - name: Earth Clay
    image: earth-clay.jpg
    color: "#1a1a1a"
  - name: Salmon Red
    image: salmon-red.jpg
    color: "#d2b48c"
  - name: Steel Grey
    image: steel-grey.jpg
    color: "#f5f5f5"
  - name: Sunset Cream
    image: sunset-cream.jpg
    color: "#f5f5f5"