name: Sync catalog-app-np

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repo A
      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # ensures full history for push

      # Step 2: Configure Git identity
      - name: Configure Git
        run: |
          git config --global user.name "Sync Bot"
          git config --global user.email "upload.blueforest@gmail.com"

      # Step 3: Add remote for Repo B using fine-grained PAT
      - name: Add remote for catalog-app-np
        run: |
          echo "🔗 Adding remote for catalog-app-np"
          git remote add catalog-app-np https://x-access-token:${{ secrets.SYNC_REPO_TOKEN }}@github.com/blue4st/catalog-app-np.git

      # Step 4: Push changes to Repo B
      - name: Push to catalog-app-np
        run: |
          echo "📤 Pushing changes to catalog-app-np main branch"
          git fetch catalog-app-np
          git push catalog-app-np main --force
